#!/usr/bin/make -f

image=x11
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=number_display=27 \
	--build-arg=number_screen=0 \
	--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

runargs=--env=ENABLE_FLUXBOX=true \
	--env=ENABLE_NOVNC=true \
	--publish-all
