#!/bin/bash

# Note: This is needed because supervisord:
#	1. Does not populate login environment variables (e.g. HOME) when performing setuid.
#	2. Does not support dynamically evaluating environment variable (i.e "HOME=/root" vs "HOME=/home/user").
#	3. There is no need to re-implement what "su" already does.
export X11_RUN_AS_ENV_ALLOWLIST="${X11_RUN_AS_ENV_ALLOWLIST:-DISPLAY}"
exec /bin/su --command="$*" --login --whitelist-environment="${X11_RUN_AS_ENV_ALLOWLIST}" "${X11_UNAME}"

